version: '3.8'

services:
  postgres-test:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - blogbowl_test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

  redis-test:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - blogbowl_test_redis_data:/data
    ports:
      - "6381:6379"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

volumes:
  blogbowl_test_postgres_data:
  blogbowl_test_redis_data:
