test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

s3:
  service: S3
  access_key_id: <%= Rails.application.credentials[:s3][:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials[:s3][:secret_access_key] %>
  endpoint: <%= Rails.application.credentials[:s3][:endpoint] %>
  region: <%= Rails.application.credentials[:s3][:region] %>
  bucket: <%= Rails.application.credentials[:s3][:bucket] %>