test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

s3:
  service: S3
  access_key_id: <%= ENV.fetch('S3_ACCESS_KEY_ID', Rails.application.credentials.dig(Rails.env.to_sym, :s3, :access_key_id)) %>
  secret_access_key: <%= ENV.fetch('S3_SECRET_ACCESS_KEY', Rails.application.credentials.dig(Rails.env.to_sym, :s3, :secret_access_key)) %>
  endpoint: <%= ENV.fetch('S3_ENDPOINT', Rails.application.credentials.dig(Rails.env.to_sym, :s3, :endpoint)) %>
  region: <%= ENV.fetch('S3_REGION', Rails.application.credentials.dig(Rails.env.to_sym, :s3, :region)) %>
  bucket: <%= ENV.fetch('S3_BUCKET', Rails.application.credentials.dig(Rails.env.to_sym, :s3, :bucket)) %>